language: ruby
rvm:
- 2.3.3

script: ./ci/tets-jekyll.sh

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

notifications:
  webhooks: https://hooks.aethonan.pro/travisci/-1001061475099/
  
sudo: false 